#!/usr/bin/env -S npx tsx
/**
 * Rebuild the `output/all-stickers/` browse view — a flat, dimension-
 * grouped gallery of every sticker's PNG, via symlinks into the real
 * per-sticker folder.
 *
 * Why this exists
 * ───────────────
 * Each sticker lives in its own subfolder under
 * `packs/journals/prax-journal/stickers/<name>/<name>.png` so the
 * per-sticker README/SVG stays colocated with its output. That's great
 * for authoring, but painful when you want to eyeball the whole pack
 * at once or compare everything at one canvas size.
 *
 * This script creates:
 *
 *   output/all-stickers/
 *   ├── all/                 (every sticker, mixed dimensions)
 *   ├── compact-400x600/     (each PNG is 1600×2400 @4×)
 *   ├── standard-600x600/    (each PNG is 2400×2400 @4×)
 *   └── expanded-800x600/    (each PNG is 3200×2400 @4×)
 *
 * populated with symlinks so:
 *   - no duplicate bytes on disk
 *   - re-running `npm run build:stickers` auto-refreshes the gallery
 *
 * Usage:
 *   npx tsx scripts/rebuild-all-stickers-index.ts
 *
 * Safe to re-run; the symlinks are overwritten each time.
 */

import { readdirSync, statSync, mkdirSync, existsSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, '..');
const STICKERS = path.join(REPO, 'packs/journals/prax-journal/stickers');
const GALLERY = path.join(REPO, 'output/all-stickers');

// ─── Dimension classifier ───────────────────────────────────────
//
// Each sticker renders at @4× raster scale. We read the PNG's actual
// pixel dims via `sips` (macOS-native, no extra deps) and bucket by
// the known size-class matrix:
//
//   compact   400×600   →  1600×2400
//   standard  600×600   →  2400×2400
//   expanded  800×600   →  3200×2400
//
// `sips` is macOS-only but this whole pack is macOS-targeted (Apple
// Pencil + GoodNotes) and we already depend on `sharp` which pulls
// native image libs. If you port this to Linux, swap to `identify`
// (imagemagick) or read PNG IHDR chunk directly.

interface Bucket {
  dirName: string;
  whenRasterWidth: number;
  whenRasterHeight: number;
}

const BUCKETS: Bucket[] = [
  { dirName: 'compact-400x600',  whenRasterWidth: 1600, whenRasterHeight: 2400 },
  { dirName: 'standard-600x600', whenRasterWidth: 2400, whenRasterHeight: 2400 },
  { dirName: 'expanded-800x600', whenRasterWidth: 3200, whenRasterHeight: 2400 },
];

function pngDims(absPath: string): { w: number; h: number } | null {
  try {
    const stdout = execFileSync('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', absPath], {
      encoding: 'utf8',
    });
    // `sips` output looks like:
    //   pixelWidth: 1600
    //   pixelHeight: 2400
    const w = Number(/pixelWidth:\s*(\d+)/.exec(stdout)?.[1] ?? 0);
    const h = Number(/pixelHeight:\s*(\d+)/.exec(stdout)?.[1] ?? 0);
    if (!w || !h) return null;
    return { w, h };
  } catch {
    return null;
  }
}

function bucketFor(w: number, h: number): Bucket | null {
  return BUCKETS.find((b) => b.whenRasterWidth === w && b.whenRasterHeight === h) ?? null;
}

// ─── README content ─────────────────────────────────────────────

function writeReadme(totals: Record<string, number>): void {
  const bucketRows = BUCKETS.map(
    (b) => `├── ${b.dirName.padEnd(22)} ${String(totals[b.dirName] ?? 0).padStart(2)} stickers`,
  ).join('\n');
  const allRow = `├── ${'all'.padEnd(22)} ${String(totals.all ?? 0).padStart(2)} stickers (every sticker, mixed dims)`;
  const rows = `${allRow}\n${bucketRows}`;

  const body = `# All Stickers — browse view

Symlinked gallery of the 60-sticker Prax Journal pack — available two ways:

- **\`all/\`** — every sticker in one flat folder (mixed dimensions)
- **\`compact-400x600/\`, \`standard-600x600/\`, \`expanded-800x600/\`** —
  grouped by canvas size so you can eyeball a whole dimension-class at once
  without Preview rescaling between images

Regenerate any time with:

\`\`\`bash
npx tsx scripts/rebuild-all-stickers-index.ts
\`\`\`

## Layout

\`\`\`
output/all-stickers/
${rows}
\`\`\`

Each file is a **symlink** into \`packs/journals/prax-journal/stickers/<name>/<name>.png\`
— no duplicate bytes on disk. PNGs are regenerated by \`npm run build:stickers\`,
so these symlinks keep pointing at the latest renders automatically.

## Open them

\`\`\`bash
open output/all-stickers/all/                   # everything (60) in one folder
open output/all-stickers/compact-400x600/       # compact stickers in Finder grid
open output/all-stickers/standard-600x600/      # standards
open output/all-stickers/expanded-800x600/      # expanded
\`\`\`

Or open any PNG in Preview and use ⌘-↑ / ⌘-↓ to walk the set.

## Archetypes (four curated skeuo families)

See \`docs/plan-ceo-review-sticker-expansion-v1.md\` for the evidence-backed
roster and the family → archetype mapping.

- **field-note** — tape + pin + date-stamp + leaf · ADHD / behavioural / habit
- **ledger** — wax-seal + thumbprint · tracking / screener / quant
- **herbarium** — pressed-leaf + sprig · savouring / positive-psych / somatic
- **clinic** — rubber-stamp + date-stamp + thread · CBT / DBT / OCD / ERP / medical

*Classification done via \`sips -g pixelWidth -g pixelHeight\`:*
- *compact = 1600×2400 @4×*
- *standard = 2400×2400 @4×*
- *expanded = 3200×2400 @4×*
`;
  writeFileSync(path.join(GALLERY, 'README.md'), body);
}

// ─── Main ───────────────────────────────────────────────────────

function main(): void {
  // Fresh start — delete any old directory so stale symlinks don't
  // linger across dimension changes.
  if (existsSync(GALLERY)) {
    rmSync(GALLERY, { recursive: true, force: true });
  }
  mkdirSync(GALLERY, { recursive: true });
  mkdirSync(path.join(GALLERY, 'all'), { recursive: true });
  for (const b of BUCKETS) {
    mkdirSync(path.join(GALLERY, b.dirName), { recursive: true });
  }

  // Walk every sticker subfolder.
  const subs = readdirSync(STICKERS).filter((name) => {
    const full = path.join(STICKERS, name);
    return statSync(full).isDirectory();
  });

  const tallies: Record<string, number> = {};
  const unclassified: string[] = [];

  for (const name of subs) {
    const pngPath = path.join(STICKERS, name, `${name}.png`);
    if (!existsSync(pngPath)) continue;

    const dims = pngDims(pngPath);
    if (!dims) {
      unclassified.push(`${name} (sips failed)`);
      continue;
    }
    const bucket = bucketFor(dims.w, dims.h);
    if (!bucket) {
      unclassified.push(`${name} (${dims.w}×${dims.h} — unknown dim)`);
      continue;
    }

    // Path from BUCKET/dirName back up to REPO, then down to the PNG.
    // `../../../` takes us out of:  output/all-stickers/<bucket>/<file>
    //                              ^-------^-----------^----------^
    const rel = path.relative(path.join(GALLERY, bucket.dirName), pngPath);
    const link = path.join(GALLERY, bucket.dirName, `${name}.png`);
    if (existsSync(link)) rmSync(link, { force: true });
    symlinkSync(rel, link);

    // Also mirror into the flat `all/` folder so every sticker is
    // browseable from one place regardless of canvas size.
    const flatRel = path.relative(path.join(GALLERY, 'all'), pngPath);
    const flatLink = path.join(GALLERY, 'all', `${name}.png`);
    if (existsSync(flatLink)) rmSync(flatLink, { force: true });
    symlinkSync(flatRel, flatLink);

    tallies[bucket.dirName] = (tallies[bucket.dirName] ?? 0) + 1;
    tallies.all = (tallies.all ?? 0) + 1;
  }

  writeReadme(tallies);

  // ── Ledger ──
  console.log(`\nRebuilt gallery at output/all-stickers/\n`);
  console.log(`  ${'all'.padEnd(22)} → ${tallies.all ?? 0} stickers (flat)`);
  for (const b of BUCKETS) {
    console.log(`  ${b.dirName.padEnd(22)} → ${tallies[b.dirName] ?? 0} stickers`);
  }
  const bucketTotal = BUCKETS.reduce((a, b) => a + (tallies[b.dirName] ?? 0), 0);
  console.log(`\n  ${'TOTAL'.padEnd(22)} → ${bucketTotal} stickers`);
  if (unclassified.length > 0) {
    console.log(`\n  unclassified (no matching bucket):`);
    for (const u of unclassified) console.log(`    - ${u}`);
  }
}

main();
